apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-chatter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: microservice-chatter
    spec:
      containers:
      - name: microservice-chatter
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chatter-service
  labels:
    app: chatter-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: microservice-chatter
