apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
      restartPolicy: Always
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: redis
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.ng.bluemix.net/<namespace>/bluechatter_app
        ports:
        - containerPort: 80
        - containerPort: 8080
      restartPolicy: Always
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatter-service
  name: chatter-service
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    nodePort: 30089
  selector:
    app: web
