apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-student-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-student
  template:
    metadata:
      labels:
        app: hello-student
    spec:
      containers:
        - name: hello-student
          image: us.icr.io/cr-student/hello-student:v1
          resources:
            limits:
              memory: "100Mi"
              cpu: "125m"
            requests:
              memory: "100Mi"
              cpu: "125m"
          ports:
            - containerPort: 3000
